### PR TITLE
railties 5.1

### PR DESCRIPTION
**Pull request by dzivalli**
That will allow to update rails to version 5.1

### CODE REVIEW

**Comment by allanbreyes** [comment]
Thanks!

**Comment by esb** [comment]
This update has not yet been pushed to rubygems. Installing version 0.0.7 from there shows that this change has not been included, making it impossible to install under rails 5.1.

**Comment by allanbreyes** [comment]
@prophittcorey can you publish this when you get a chance? Thanks!

**Comment by allanbreyes** [comment]
@prophittcorey, kindly disregard... looks like I published to RubyGems under my account. I forked and pushed to https://github.com/allanbreyes/activeadmin_json_editor... I'm happy to take on maintenance for this, since it looks like Udacity won't need this any more. :beers:

@esb I'll push up `0.0.7` to RubyGems today. Thanks for flagging!

*edit*: looks like `0.0.7` was a borked build, so I yanked it. Should be available on `0.0.8`.

**Pull request merged**
